In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.DataFrame({
    'text': ["people watch campusx","campusx a a a a watch campusx","people write comment","campusx write comment"],
    'output': [1,1,0,0]
})

In [3]:
df

text  output
0           people watch campusx       1
1  campusx a a a a watch campusx       1
2           people write comment       0
3          campusx write comment       0

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
#OR cv=CountVectorizer(ngram_range=(1,1))

In [5]:
bow=cv.fit_transform(df['text'])

In [6]:
print(cv.vocabulary_) #vocabulary_  is an attribute in this class to find unique vocabulary. Each word is assigned a column index and Order is decided internally

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}


In [7]:
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 1 1 0]]
[[2 0 0 1 0]]


In [8]:
cv.transform(["campusx watch and write comment of campusx"]).toarray()    #'and' and 'of' were OOV but the fact that we didn't had these in our training, here these didn't count

array([[2, 1, 0, 1, 1]])

In [9]:
bi_cv=CountVectorizer(ngram_range=(2,2)) #Bi-gram

In [10]:
bigram=bi_cv.fit_transform(df['text'])

In [11]:
print(bi_cv.vocabulary_)

{'people watch': 2, 'watch campusx': 4, 'campusx watch': 0, 'people write': 3, 'write comment': 5, 'campusx write': 1}


In [12]:
print(bigram[0].toarray())


[[0 0 1 0 1 0]]


In [13]:
tri_cv=CountVectorizer(ngram_range=(3,3)) #Tri-gram

In [14]:
trigram=tri_cv.fit_transform(df['text'])

In [15]:
print(tri_cv.vocabulary_)

{'people watch campusx': 2, 'campusx watch campusx': 0, 'people write comment': 3, 'campusx write comment': 1}


In [16]:
print(trigram[0].toarray())
print(trigram[1].toarray())
print(trigram[2].toarray())
print(trigram[3].toarray())

[[0 0 1 0]]
[[1 0 0 0]]
[[0 0 0 1]]
[[0 1 0 0]]


In [17]:
#range= 1 to 3 all combinations
n_cv=CountVectorizer(ngram_range=(1,3))

In [18]:
ngram=n_cv.fit_transform(df['text'])

In [19]:
print(n_cv.vocabulary_)
print(len(n_cv.vocabulary_))

{'people': 6, 'watch': 11, 'campusx': 0, 'people watch': 7, 'watch campusx': 12, 'people watch campusx': 8, 'campusx watch': 1, 'campusx watch campusx': 2, 'write': 13, 'comment': 5, 'people write': 9, 'write comment': 14, 'people write comment': 10, 'campusx write': 3, 'campusx write comment': 4}
15


In [20]:
print(ngram[0].toarray())
print(ngram[1].toarray())
print(ngram[2].toarray())
print(ngram[3].toarray())

[[1 0 0 0 0 0 1 1 1 0 0 1 1 0 0]]
[[2 1 1 0 0 0 0 0 0 0 0 1 1 0 0]]
[[0 0 0 0 0 1 1 0 0 1 1 0 0 1 1]]
[[1 0 0 1 1 1 0 0 0 0 0 0 0 1 1]]


In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [22]:
tfidf=TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()

array([[0.49681612, 0.        , 0.61366674, 0.61366674, 0.        ],
       [0.8508161 , 0.        , 0.        , 0.52546357, 0.        ],
       [0.        , 0.57735027, 0.57735027, 0.        , 0.57735027],
       [0.49681612, 0.61366674, 0.        , 0.        , 0.61366674]])

In [23]:
print(tfidf.idf_)   #IDF of each unique word
print(tfidf.get_feature_names_out())

[1.22314355 1.51082562 1.51082562 1.51082562 1.51082562]
['campusx' 'comment' 'people' 'watch' 'write']
